# Generated by Django 4.0.2 on 2022-03-07 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
